# Array creation

Numpy array from a list

In [1]:
import numpy as np

np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

2-D numpy arrays can be created from lists or tuples

In [2]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.array(((1, 2, 3), (4, 5, 6)))

array([[1, 2, 3],
       [4, 5, 6]])

Helper methods let us create arrays filled with zeros, ones or create identity matrix

In [4]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones(3)

array([1., 1., 1.])

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Create an array with a range of numbers

In [28]:
# step
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

Create an array of evenly spaced values over a specified range. 

This function is useful for charts to create X samples

In [32]:
# elements
np.linspace(1, 10, 50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

# Manipulation

Changing array shape

In [55]:
a = np.array(((1, 2, 3), (5, 6, 7)))
print(a)

a.reshape(3, 2)

[[1 2 3]
 [5 6 7]]


array([[1, 2],
       [3, 5],
       [6, 7]])

Numpy provides two methods for flattening arrays - `flatten` and `ravel`, however `flatten` copies elements, while `ravel` tries to reuse them.

In [56]:
a.flatten()

array([1, 2, 3, 5, 6, 7])

In [57]:
a.ravel()

array([1, 2, 3, 5, 6, 7])

each array can be easily transposed with .T

In [15]:
a.T

array([[1, 5],
       [2, 6],
       [3, 7]])

# Math operations

Operator overload facilitates working with arrays, but traditional methods still exist ;)

In [19]:
a

array([[1, 2, 3],
       [5, 6, 7]])

In [43]:
a + a       # np.add(a, a)

array([[ 2,  4,  6],
       [10, 12, 14]])

In [45]:
a - a

array([[0, 0, 0],
       [0, 0, 0]])

In [46]:
a*a

array([[ 1,  4,  9],
       [25, 36, 49]])

In [47]:
a/a

array([[1., 1., 1.],
       [1., 1., 1.]])

### Dot product 

Dot product $a⋅b=∥a∥∥b∥cos(θ)$ has several interpretations and uses:

1. Projection: One vector's dot product with another indicates how much of the first vector lies along the second vector. It's the length of the projection of one vector onto another. If you take the dot product of a vector with itself, you get the square of its length.

2. Similarity: In machine learning, especially in natural language processing, the dot product between two vectors often represents similarity. If the vectors represent the embedding of words or documents, a higher dot product indicates more similarity between the two entities. 

3. Angles and Orthogonality: The dot product tells us about the angle between two vectors. If the dot product is zero, the vectors are orthogonal 

In [68]:
print(a)
np.dot(a, [10, 20, 30])

[[1 2 3]
 [5 6 7]]


array([140, 380])

In [52]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.95892427, -0.2794155 ,  0.6569866 ]])

## Broadcasting

Broadcasting simplifies performing operations on smaller arrays

In [23]:
a

array([[1, 2, 3],
       [5, 6, 7]])

In [26]:
a + [1]  # 1 will be added to all elements

array([[2, 3, 4],
       [6, 7, 8]])

In [28]:
a + [2, 2, 3]  # [2, 2, 3] vector will be added to all elements

array([[ 3,  4,  6],
       [ 7,  8, 10]])

# Statistical methods

In [64]:
np.mean(a)

4.0

In [65]:
np.median(a)

4.0

In [66]:
np.std(a)

2.160246899469287

In [67]:
np.var(a)

4.666666666666667

In [70]:
np.std(a)

2.160246899469287

In [71]:
np.min(a)

1

In [72]:
np.max(a)

7

## Axis

Some operations behave differently, depending on the selected axis

![](https://numpy.org/doc/stable/_images/np_matrix_aggregation_row.png)

In [30]:
a

array([[1, 2, 3],
       [5, 6, 7]])

In [93]:
np.max(a, axis=0)

array([5, 6, 7])

In [95]:
np.max(a, axis=1)

array([3, 7])

argmax/argmin return indexes of elements with max/min values

In [37]:
b = np.array([[10, 5, 20], [60, 9, 13]])
b

array([[10,  5, 20],
       [60,  9, 13]])

In [38]:
np.argmax(b)

3

# Conditions

Conditional operators returns an array of the same size with boolean values

In [46]:
a < 5

array([[ True,  True,  True],
       [False, False, False]])

Conditionals can be also used as indexes to retrieve data

In [47]:
a[a < 5]

array([1, 2, 3])

Conditionals can be formed into larger expressions with:
- `&` AND
- `|` OR
but keep in mind, you have to put them into parentheses, as `&` and `|` have lower precedence

In [48]:
a[(a > 2) & (a < 5)]

array([3])

## if/then/else 
where(condition, then, else)

In [49]:
a

array([[1, 2, 3],
       [5, 6, 7]])

`where` can replace elements if condition is met/unmet

In [52]:
np.where(a < 5, a, 0)

array([[1, 2, 3],
       [0, 0, 0]])